export const routes = {
  faq: 'Faq',
  shop: 'Shop',
  dish: 'Dish',
  order: 'Order',
  signIn: 'SignIn',
  signUp: 'SignUp',
  profile: 'Profile',
  reviews: 'Reviews',
  wishlist: 'Wishlist',
  checkout: 'Checkout',
  cartEmpty: 'CartEmpty',
  onboarding: 'Onboarding',
  RootLayout: 'RootLayout',
  editProfile: 'EditProfile',
  newPassword: 'NewPassword',
  shopCategory: 'ShopCategory',
  orderHistory: 'OrderHistory',
  myPromocodes: 'MyPromocodes',
  commentReply: 'CommentReply',
  leaveAReview: 'LeaveAReview',
  wishlistEmpty: 'WishlistEmpty',
  notifications: 'Notifications',
  accountCreated: 'AccountCreated',
  changePassword: 'ChangePassword',
  forgotPassword: 'ForgotPassword',
  orderSuccessful: 'OrderSuccessful',
  confirmationCode: 'ConfirmationCode',
  myPromocodesEmpty: 'MyPromocodesEmpty',
  verifyUser: 'VerifyUser',
  forgotPasswordSentEmail: 'ForgotPasswordSentEmail',

  products: 'Products',
  sweetsDetail: 'SweetsDetail',
  announcementDetail: 'AnnouncementDetail',
  accountDetail: 'AccountDetail',

} as const;
